[Frontend] Sign-up window
krlls/stream-bridge pull request #59
Opened 2023-08-01 13:07 UTC by dvnotam

2023-08-01 13:17 UTC, krlls requested changes

2023-08-01 13:17 UTC, krlls commented on apps/web/src/App/Pages/Auth/SignUp/index.tsx
> +                  <UnlockIcon marginRight={2} />
Можно иконку на что-то [другое](https://chakra-ui.com/docs/components/icon/usage) поменять, так как это регистрация

2023-08-01 13:17 UTC, krlls commented on apps/web/src/localization/langs/en.ts
> +  RepeatPassword: 'Repeat the password',
Обычно без "the"

2023-08-01 13:17 UTC, krlls commented on apps/web/src/localization/langs/en.ts
> +  YourRepeatPassword: 'Your repeat the password',
Тут тоже 

> Обычно без "the"

2023-08-01 13:17 UTC, krlls commented on apps/web/src/App/Pages/Auth/SignUp/index.tsx
> +                <FormHelperText>{t(d.YourRepeatPassword)}</FormHelperText>
Наверное можно убрать

2023-08-01 13:25 UTC, krlls requested changes

2023-08-01 13:25 UTC, krlls commented on apps/web/src/App/Pages/Auth/SignUp/index.tsx
>  export const SignUp: FC = () => {
- Вынеси форму в отдельный компонент в папку components, можно назвать `UserForm`.
- Обращение к api как пропс можно будет передать уже из `Pages`.
- Напиши историю по аналогии с `apps/web/src/components/ListOfPlaylists`

2023-08-05 19:20 UTC, dvnotam commented
Вкладка Sign-Up. Регистрация

2023-08-05 19:21 UTC, dvnotam commented
Sign-Up window, registration

2023-08-07 19:26 UTC, krlls requested changes

2023-08-07 19:26 UTC, krlls commented on apps/web/src/App/Pages/Auth/SignUp/index.tsx
> +                    minLength: { value: 1, message: t(d.MinimumLengthShould) },
Добавь ограничение на максимальную длину до 30 символов

2023-08-07 19:26 UTC, krlls commented on apps/web/src/App/Pages/Auth/SignUp/index.tsx
> +                      value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
Вынести в утилиты и поменять в login тоже

2023-08-07 19:26 UTC, krlls commented on apps/web/src/App/Pages/Auth/SignUp/index.tsx
> +                    minLength: { value: 4, message: t(d.MinimumLengthShould) },
Тоже вынести в утилиты и поменять в Логине

2023-08-07 19:26 UTC, krlls commented on apps/web/src/App/Pages/Auth/SignUp/index.tsx
> +                        return 'Passwords not match'
Добавить перевод

2023-08-07 19:26 UTC, krlls commented on apps/web/src/App/Pages/Auth/SignIn/index.tsx
> +import { RegularEmailValidation } from '../../../../utils/utils.ts'
Назови validation, туда и регулярку положи и константы для минимальной/максимальной длины полей

2023-08-07 19:26 UTC, krlls commented on apps/web/src/App/Pages/Auth/SignUp/index.tsx
> +import { useLocalization } from '../../../../hooks/useLocalization.ts'
Поправь импорты: должно быть без .ts (как в остальных местах)
```suggestion
import { useLocalization } from '../../../../hooks/useLocalization'
```

2023-08-07 19:26 UTC, krlls commented on apps/web/src/App/Pages/Auth/SignUp/index.tsx
> +import { RegularEmailValidation } from '../../../../utils/utils.ts'
> должно быть без .ts

2023-08-10 01:26 UTC, krlls requested changes

2023-08-10 01:26 UTC, krlls commented on apps/web/src/utils/vaidation.ts
> +export const MinimalLength = (t: any, d: any) => {
Тут не нужно функцией, сделай просто константой 
```suggestion
export const MIN_PASS_LENGTH = 1
export const MAX_NAME_LENGTH = 30
```

2023-08-10 01:26 UTC, krlls commented on apps/web/src/utils/vaidation.ts
> +export const MaximumLength = (t: any, d: any) => {
Здесь тоже самое

2023-08-10 01:56 UTC, krlls commented on apps/web/src/App/Pages/Auth/SignUp/index.tsx
> +                    validate: (val) => {
Давай вот так сократим:
```suggestion
                    (val) => password === val || t(d.PasswordsNotMatch)
```

2023-08-10 01:57 UTC, krlls requested changes

2023-08-10 01:57 UTC, krlls commented on apps/web/src/App/Pages/Auth/SignUp/index.tsx
> +                <FormErrorMessage>{errors.password && errors.password.message}</FormErrorMessage>
Здесь неверное название поля: у тебя тут должно быть `repeatPassword`

2023-08-10 15:48 UTC, krlls approved these changes

2023-08-10 15:49 UTC, merged