added PWA functionality
krlls/stream-bridge pull request #97
Opened 2023-09-29 15:39 UTC by dvnotam

2023-09-29 15:45 UTC, dvnotam commented
Добавил vite_pwa. Пока все иконки в паблике, попробую перенести в src/assets

2023-09-29 17:41 UTC, krlls requested changes

2023-09-29 17:41 UTC, krlls commented on apps/web/index.html
> +    <meta name="description" content="My Awesome Stream-Bridge">
Добавь это: 

_Music synchronization tool that allows users to sync music from various streaming services._

Можно сократить еще немного

2023-09-29 17:41 UTC, krlls commented on apps/web/index.html
> +    <link rel="mask-icon" href="/assets/safari-pinned-tab.svg" color="#5bbad5">
Возьми фоновый цвет из иконки

2023-09-29 17:41 UTC, krlls commented on apps/web/vite.config.ts
> +        description: 'My Awesome Stream-Bridge description',
Тут тоже

2023-09-29 17:41 UTC, krlls commented on apps/web/vite.config.ts
> +        theme_color: '#ffffff',
Тут можно цвет из иконки или фоновый из приложения

2023-09-29 17:41 UTC, krlls commented on apps/web/public/assets/site.webmanifest
> +    "background_color": "#ffffff",
Здесь цвет фона приложения

2023-09-29 17:41 UTC, krlls commented on apps/web/public/assets/site.webmanifest
> +    "theme_color": "#ffffff",
Здесь цвет хедера из приложения

2023-09-29 17:41 UTC, krlls commented on apps/web/public/assets/site.webmanifest
> +    "name": "",
Stream Bridge

2023-09-29 17:41 UTC, krlls commented on apps/web/public/assets/site.webmanifest
> +    "short_name": "",
SBridge

2023-09-29 17:41 UTC, krlls commented on apps/web/public/assets/site.webmanifest
Проверь, работает ли без него

2023-09-29 17:44 UTC, krlls requested changes

2023-09-29 17:44 UTC, krlls commented on apps/web/public/assets/safari-pinned-tab.svg
А почему тут выразано?

2023-10-02 18:09 UTC, krlls approved these changes

2023-10-02 18:10 UTC, krlls requested changes
Проверь, работает ли без манифеста в assets

2023-11-05 18:00 UTC, krlls approved these changes

2023-11-05 18:06 UTC, merged